# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../_sandbox/maya/scripts/ui/qt/report.ui'
#
# Created: Thu Aug 20 17:16:48 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_report(object):
    def setupUi(self, report):
        report.setObjectName("report")
        report.resize(451, 250)
        report.setMinimumSize(QtCore.QSize(451, 0))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        report.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/btn/img/btn/mailBtn24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        report.setWindowIcon(icon)
        report.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(31, 31, 31);")
        self.edtScript = QtGui.QLineEdit(report)
        self.edtScript.setGeometry(QtCore.QRect(10, 47, 431, 26))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.edtScript.setFont(font)
        self.edtScript.setText("")
        self.edtScript.setReadOnly(False)
        self.edtScript.setObjectName("edtScript")
        self.btnReport = QtGui.QPushButton(report)
        self.btnReport.setGeometry(QtCore.QRect(360, 140, 81, 41))
        self.btnReport.setStyleSheet("background-color: rgb(56, 56, 56);")
        self.btnReport.setText("")
        self.btnReport.setIcon(icon)
        self.btnReport.setIconSize(QtCore.QSize(32, 32))
        self.btnReport.setObjectName("btnReport")
        self.btnCancel = QtGui.QPushButton(report)
        self.btnCancel.setGeometry(QtCore.QRect(360, 190, 81, 26))
        self.btnCancel.setStyleSheet("background-color: rgb(56, 56, 56);")
        self.btnCancel.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/btn/img/btn/denialBtn24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCancel.setIcon(icon1)
        self.btnCancel.setIconSize(QtCore.QSize(23, 23))
        self.btnCancel.setObjectName("btnCancel")
        self.edtComment = QtGui.QPlainTextEdit(report)
        self.edtComment.setGeometry(QtCore.QRect(10, 50, 431, 77))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.edtComment.setFont(font)
        self.edtComment.setStyleSheet("color: rgb(175, 175, 175);")
        self.edtComment.setFrameShape(QtGui.QFrame.Box)
        self.edtComment.setFrameShadow(QtGui.QFrame.Plain)
        self.edtComment.setLineWidth(1)
        self.edtComment.setMidLineWidth(0)
        self.edtComment.setBackgroundVisible(False)
        self.edtComment.setCenterOnScroll(False)
        self.edtComment.setObjectName("edtComment")
        self.edtErrorMsg = QtGui.QPlainTextEdit(report)
        self.edtErrorMsg.setGeometry(QtCore.QRect(10, 137, 341, 81))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.edtErrorMsg.setFont(font)
        self.edtErrorMsg.setStyleSheet("color: rgb(175, 175, 175);")
        self.edtErrorMsg.setFrameShape(QtGui.QFrame.Box)
        self.edtErrorMsg.setFrameShadow(QtGui.QFrame.Plain)
        self.edtErrorMsg.setLineWidth(1)
        self.edtErrorMsg.setMidLineWidth(0)
        self.edtErrorMsg.setBackgroundVisible(False)
        self.edtErrorMsg.setCenterOnScroll(False)
        self.edtErrorMsg.setObjectName("edtErrorMsg")
        self.btnHelp = QtGui.QPushButton(report)
        self.btnHelp.setGeometry(QtCore.QRect(425, 225, 16, 16))
        self.btnHelp.setStyleSheet("background-color: rgb(56, 56, 56);")
        self.btnHelp.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/btn/img/btn/helpBtn24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnHelp.setIcon(icon2)
        self.btnHelp.setIconSize(QtCore.QSize(16, 16))
        self.btnHelp.setObjectName("btnHelp")
        self.edtMsg = QtGui.QLineEdit(report)
        self.edtMsg.setEnabled(True)
        self.edtMsg.setGeometry(QtCore.QRect(10, 225, 336, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.edtMsg.setFont(font)
        self.edtMsg.setFrame(False)
        self.edtMsg.setReadOnly(True)
        self.edtMsg.setObjectName("edtMsg")
        self.lblUser = QtGui.QLabel(report)
        self.lblUser.setGeometry(QtCore.QRect(360, 225, 16, 16))
        self.lblUser.setStyleSheet("background-color: \'transparent\';")
        self.lblUser.setText("")
        self.lblUser.setPixmap(QtGui.QPixmap(":/user/img/user/_default.png"))
        self.lblUser.setScaledContents(True)
        self.lblUser.setObjectName("lblUser")
        self.lblReport = QtGui.QLabel(report)
        self.lblReport.setGeometry(QtCore.QRect(10, 10, 30, 30))
        self.lblReport.setStyleSheet("background-color: \'transparent\';")
        self.lblReport.setText("")
        self.lblReport.setPixmap(QtGui.QPixmap(":/shelf/img/shelf/shelf_bug35.png"))
        self.lblReport.setScaledContents(True)
        self.lblReport.setObjectName("lblReport")
        self.cbxReport = QtGui.QComboBox(report)
        self.cbxReport.setEnabled(True)
        self.cbxReport.setGeometry(QtCore.QRect(45, 14, 136, 22))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.cbxReport.setFont(font)
        self.cbxReport.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cbxReport.setStyleSheet("background-color: rgb(56, 56, 56);")
        self.cbxReport.setEditable(False)
        self.cbxReport.setInsertPolicy(QtGui.QComboBox.InsertAtBottom)
        self.cbxReport.setFrame(False)
        self.cbxReport.setObjectName("cbxReport")
        self.cbxScript = QtGui.QComboBox(report)
        self.cbxScript.setGeometry(QtCore.QRect(235, 15, 206, 22))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.cbxScript.setFont(font)
        self.cbxScript.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cbxScript.setStyleSheet("background-color: rgb(56, 56, 56);")
        self.cbxScript.setEditable(False)
        self.cbxScript.setInsertPolicy(QtGui.QComboBox.InsertAtBottom)
        self.cbxScript.setFrame(False)
        self.cbxScript.setModelColumn(0)
        self.cbxScript.setObjectName("cbxScript")
        self.lblScript = QtGui.QLabel(report)
        self.lblScript.setGeometry(QtCore.QRect(200, 10, 30, 30))
        self.lblScript.setStyleSheet("background-color: \'transparent\';")
        self.lblScript.setText("")
        self.lblScript.setPixmap(QtGui.QPixmap(":/shelf/img/shelf/shelf_default35.png"))
        self.lblScript.setScaledContents(True)
        self.lblScript.setObjectName("lblScript")
        self.btnShowReport = QtGui.QPushButton(report)
        self.btnShowReport.setGeometry(QtCore.QRect(400, 225, 16, 16))
        self.btnShowReport.setStyleSheet("background-color: rgb(56, 56, 56);")
        self.btnShowReport.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/shelf/img/shelf/shelf_outliner35.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnShowReport.setIcon(icon3)
        self.btnShowReport.setIconSize(QtCore.QSize(16, 16))
        self.btnShowReport.setObjectName("btnShowReport")
        self.btnBefore = QtGui.QPushButton(report)
        self.btnBefore.setGeometry(QtCore.QRect(360, 140, 36, 41))
        self.btnBefore.setStyleSheet("background-color: rgb(56, 56, 56);")
        self.btnBefore.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/btn/img/btn/btnArrowLeft48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBefore.setIcon(icon4)
        self.btnBefore.setIconSize(QtCore.QSize(32, 32))
        self.btnBefore.setObjectName("btnBefore")
        self.btnNext = QtGui.QPushButton(report)
        self.btnNext.setEnabled(True)
        self.btnNext.setGeometry(QtCore.QRect(405, 140, 36, 41))
        self.btnNext.setStyleSheet("background-color: rgb(56, 56, 56);")
        self.btnNext.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/btn/img/btn/btnArrowRight48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNext.setIcon(icon5)
        self.btnNext.setIconSize(QtCore.QSize(32, 32))
        self.btnNext.setObjectName("btnNext")
        self.btnSaveToHistory = QtGui.QPushButton(report)
        self.btnSaveToHistory.setGeometry(QtCore.QRect(405, 190, 36, 26))
        self.btnSaveToHistory.setStyleSheet("background-color: rgb(56, 56, 56);")
        self.btnSaveToHistory.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/btn/img/btn/btnSave.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSaveToHistory.setIcon(icon6)
        self.btnSaveToHistory.setIconSize(QtCore.QSize(18, 18))
        self.btnSaveToHistory.setObjectName("btnSaveToHistory")
        self.btnFolder = QtGui.QPushButton(report)
        self.btnFolder.setGeometry(QtCore.QRect(360, 190, 36, 26))
        self.btnFolder.setStyleSheet("background-color: rgb(56, 56, 56);")
        self.btnFolder.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/btn/img/btn/folderBtn24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFolder.setIcon(icon7)
        self.btnFolder.setIconSize(QtCore.QSize(16, 16))
        self.btnFolder.setObjectName("btnFolder")

        self.retranslateUi(report)
        QtCore.QMetaObject.connectSlotsByName(report)

    def retranslateUi(self, report):
        report.setWindowTitle(QtGui.QApplication.translate("report", "Report Error", None, QtGui.QApplication.UnicodeUTF8))
        self.edtScript.setPlaceholderText(QtGui.QApplication.translate("report", "Script or Title", None, QtGui.QApplication.UnicodeUTF8))
        self.btnReport.setShortcut(QtGui.QApplication.translate("report", "Return", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCancel.setShortcut(QtGui.QApplication.translate("report", "Esc", None, QtGui.QApplication.UnicodeUTF8))
        self.edtComment.setPlainText(QtGui.QApplication.translate("report", "Comment", None, QtGui.QApplication.UnicodeUTF8))
        self.edtErrorMsg.setPlainText(QtGui.QApplication.translate("report", "Error Message", None, QtGui.QApplication.UnicodeUTF8))
        self.edtMsg.setText(QtGui.QApplication.translate("report", "Report Error: Save", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBefore.setShortcut(QtGui.QApplication.translate("report", "Return", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNext.setShortcut(QtGui.QApplication.translate("report", "Return", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSaveToHistory.setShortcut(QtGui.QApplication.translate("report", "Return", None, QtGui.QApplication.UnicodeUTF8))

import maya_rc
