# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../_sandbox/maya/scripts/ui/qt/alembicExport.ui'
#
# Created: Fri Aug 28 18:18:38 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_alembicExport(object):
    def setupUi(self, alembicExport):
        alembicExport.setObjectName("alembicExport")
        alembicExport.resize(451, 172)
        alembicExport.setMinimumSize(QtCore.QSize(451, 0))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        alembicExport.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/shelf/img/shelf/shelf_alembicExport35.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        alembicExport.setWindowIcon(icon)
        alembicExport.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(31, 31, 31);")
        self.btnExport = QtGui.QPushButton(alembicExport)
        self.btnExport.setGeometry(QtCore.QRect(360, 66, 41, 36))
        self.btnExport.setStyleSheet("background-color: rgb(56, 56, 56);")
        self.btnExport.setText("")
        self.btnExport.setIcon(icon)
        self.btnExport.setIconSize(QtCore.QSize(32, 32))
        self.btnExport.setObjectName("btnExport")
        self.btnCancel = QtGui.QPushButton(alembicExport)
        self.btnCancel.setGeometry(QtCore.QRect(360, 110, 81, 26))
        self.btnCancel.setStyleSheet("background-color: rgb(56, 56, 56);")
        self.btnCancel.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/btn/img/btn/denialBtn24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCancel.setIcon(icon1)
        self.btnCancel.setIconSize(QtCore.QSize(23, 23))
        self.btnCancel.setObjectName("btnCancel")
        self.btnHelp = QtGui.QPushButton(alembicExport)
        self.btnHelp.setGeometry(QtCore.QRect(425, 145, 16, 16))
        self.btnHelp.setStyleSheet("background-color: rgb(56, 56, 56);")
        self.btnHelp.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/btn/img/btn/helpBtn24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnHelp.setIcon(icon2)
        self.btnHelp.setIconSize(QtCore.QSize(16, 16))
        self.btnHelp.setObjectName("btnHelp")
        self.edtMsg = QtGui.QLineEdit(alembicExport)
        self.edtMsg.setEnabled(True)
        self.edtMsg.setGeometry(QtCore.QRect(10, 145, 316, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.edtMsg.setFont(font)
        self.edtMsg.setFrame(False)
        self.edtMsg.setReadOnly(True)
        self.edtMsg.setObjectName("edtMsg")
        self.lblUser = QtGui.QLabel(alembicExport)
        self.lblUser.setGeometry(QtCore.QRect(360, 145, 16, 16))
        self.lblUser.setStyleSheet("background-color: \'transparent\';")
        self.lblUser.setText("")
        self.lblUser.setPixmap(QtGui.QPixmap(":/user/img/user/_default.png"))
        self.lblUser.setScaledContents(True)
        self.lblUser.setObjectName("lblUser")
        self.lblReport = QtGui.QLabel(alembicExport)
        self.lblReport.setGeometry(QtCore.QRect(45, 84, 20, 20))
        self.lblReport.setStyleSheet("background-color: \'transparent\';")
        self.lblReport.setText("")
        self.lblReport.setPixmap(QtGui.QPixmap(":/btn/img/btn/btnCamera48.png"))
        self.lblReport.setScaledContents(True)
        self.lblReport.setObjectName("lblReport")
        self.lblScript = QtGui.QLabel(alembicExport)
        self.lblScript.setGeometry(QtCore.QRect(195, 54, 20, 20))
        self.lblScript.setStyleSheet("background-color: \'transparent\';")
        self.lblScript.setText("")
        self.lblScript.setPixmap(QtGui.QPixmap(":/shelf/img/shelf/shelf_default35.png"))
        self.lblScript.setScaledContents(True)
        self.lblScript.setObjectName("lblScript")
        self.btnReport = QtGui.QPushButton(alembicExport)
        self.btnReport.setGeometry(QtCore.QRect(400, 145, 16, 16))
        self.btnReport.setStyleSheet("background-color: rgb(56, 56, 56);")
        self.btnReport.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/btn/img/btn/mailBtn24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnReport.setIcon(icon3)
        self.btnReport.setIconSize(QtCore.QSize(16, 16))
        self.btnReport.setObjectName("btnReport")
        self.cbxCam = QtGui.QCheckBox(alembicExport)
        self.cbxCam.setGeometry(QtCore.QRect(75, 85, 70, 17))
        self.cbxCam.setChecked(True)
        self.cbxCam.setObjectName("cbxCam")
        self.cbxAssets = QtGui.QCheckBox(alembicExport)
        self.cbxAssets.setGeometry(QtCore.QRect(225, 55, 70, 17))
        self.cbxAssets.setChecked(True)
        self.cbxAssets.setObjectName("cbxAssets")
        self.cbxAssetsChar = QtGui.QCheckBox(alembicExport)
        self.cbxAssetsChar.setGeometry(QtCore.QRect(180, 85, 70, 17))
        self.cbxAssetsChar.setChecked(True)
        self.cbxAssetsChar.setObjectName("cbxAssetsChar")
        self.cbxAssetsProp = QtGui.QCheckBox(alembicExport)
        self.cbxAssetsProp.setGeometry(QtCore.QRect(180, 115, 70, 17))
        self.cbxAssetsProp.setChecked(True)
        self.cbxAssetsProp.setObjectName("cbxAssetsProp")
        self.cbxAssetsSet = QtGui.QCheckBox(alembicExport)
        self.cbxAssetsSet.setGeometry(QtCore.QRect(255, 85, 70, 17))
        self.cbxAssetsSet.setChecked(True)
        self.cbxAssetsSet.setObjectName("cbxAssetsSet")
        self.cbxAssetsFx = QtGui.QCheckBox(alembicExport)
        self.cbxAssetsFx.setGeometry(QtCore.QRect(255, 115, 70, 17))
        self.cbxAssetsFx.setChecked(True)
        self.cbxAssetsFx.setObjectName("cbxAssetsFx")
        self.lblReport_2 = QtGui.QLabel(alembicExport)
        self.lblReport_2.setGeometry(QtCore.QRect(45, 114, 20, 20))
        self.lblReport_2.setStyleSheet("background-color: \'transparent\';")
        self.lblReport_2.setText("")
        self.lblReport_2.setPixmap(QtGui.QPixmap(":/shelf/img/shelf/shelf_suggestion35.png"))
        self.lblReport_2.setScaledContents(True)
        self.lblReport_2.setObjectName("lblReport_2")
        self.cbxLight = QtGui.QCheckBox(alembicExport)
        self.cbxLight.setGeometry(QtCore.QRect(75, 115, 70, 17))
        self.cbxLight.setObjectName("cbxLight")
        self.cbxMerge = QtGui.QCheckBox(alembicExport)
        self.cbxMerge.setGeometry(QtCore.QRect(360, 15, 81, 17))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.cbxMerge.setFont(font)
        self.cbxMerge.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.cbxMerge.setChecked(True)
        self.cbxMerge.setObjectName("cbxMerge")
        self.cbxAll = QtGui.QCheckBox(alembicExport)
        self.cbxAll.setGeometry(QtCore.QRect(75, 20, 41, 17))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        self.cbxAll.setFont(font)
        self.cbxAll.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cbxAll.setChecked(False)
        self.cbxAll.setObjectName("cbxAll")
        self.btnOpenFolder = QtGui.QPushButton(alembicExport)
        self.btnOpenFolder.setGeometry(QtCore.QRect(335, 144, 16, 16))
        self.btnOpenFolder.setStyleSheet("background-color: rgb(56, 56, 56);")
        self.btnOpenFolder.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/btn/img/btn/folderBtn24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnOpenFolder.setIcon(icon4)
        self.btnOpenFolder.setIconSize(QtCore.QSize(14, 14))
        self.btnOpenFolder.setObjectName("btnOpenFolder")
        self.btnExportFx = QtGui.QPushButton(alembicExport)
        self.btnExportFx.setGeometry(QtCore.QRect(405, 66, 36, 36))
        self.btnExportFx.setStyleSheet("background-color: rgb(56, 56, 56);")
        self.btnExportFx.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/shelf/img/shelf/shelf_alembicExportFx35.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnExportFx.setIcon(icon5)
        self.btnExportFx.setIconSize(QtCore.QSize(32, 32))
        self.btnExportFx.setObjectName("btnExportFx")
        self.cbxSelected = QtGui.QCheckBox(alembicExport)
        self.cbxSelected.setGeometry(QtCore.QRect(225, 20, 76, 17))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        self.cbxSelected.setFont(font)
        self.cbxSelected.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cbxSelected.setChecked(False)
        self.cbxSelected.setObjectName("cbxSelected")
        self.edtFrameEnd = QtGui.QLineEdit(alembicExport)
        self.edtFrameEnd.setEnabled(True)
        self.edtFrameEnd.setGeometry(QtCore.QRect(405, 40, 36, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.edtFrameEnd.setFont(font)
        self.edtFrameEnd.setFrame(True)
        self.edtFrameEnd.setAlignment(QtCore.Qt.AlignCenter)
        self.edtFrameEnd.setReadOnly(False)
        self.edtFrameEnd.setObjectName("edtFrameEnd")
        self.edtFrameStart = QtGui.QLineEdit(alembicExport)
        self.edtFrameStart.setEnabled(True)
        self.edtFrameStart.setGeometry(QtCore.QRect(360, 40, 36, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.edtFrameStart.setFont(font)
        self.edtFrameStart.setFrame(True)
        self.edtFrameStart.setAlignment(QtCore.Qt.AlignCenter)
        self.edtFrameStart.setReadOnly(False)
        self.edtFrameStart.setObjectName("edtFrameStart")
        self.label = QtGui.QLabel(alembicExport)
        self.label.setGeometry(QtCore.QRect(397, 41, 8, 16))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(alembicExport)
        QtCore.QMetaObject.connectSlotsByName(alembicExport)

    def retranslateUi(self, alembicExport):
        alembicExport.setWindowTitle(QtGui.QApplication.translate("alembicExport", "Alembic Export", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExport.setShortcut(QtGui.QApplication.translate("alembicExport", "Return", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCancel.setShortcut(QtGui.QApplication.translate("alembicExport", "Esc", None, QtGui.QApplication.UnicodeUTF8))
        self.edtMsg.setText(QtGui.QApplication.translate("alembicExport", "ALEMBIC EXPORT | Selectiv", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxCam.setText(QtGui.QApplication.translate("alembicExport", "CAM", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxAssets.setText(QtGui.QApplication.translate("alembicExport", "ASSETS", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxAssetsChar.setText(QtGui.QApplication.translate("alembicExport", "char", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxAssetsProp.setText(QtGui.QApplication.translate("alembicExport", "prop", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxAssetsSet.setText(QtGui.QApplication.translate("alembicExport", "set", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxAssetsFx.setText(QtGui.QApplication.translate("alembicExport", "fx", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxLight.setText(QtGui.QApplication.translate("alembicExport", "LIGHT", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxMerge.setText(QtGui.QApplication.translate("alembicExport", "merge", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxAll.setText(QtGui.QApplication.translate("alembicExport", "ALL", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExportFx.setShortcut(QtGui.QApplication.translate("alembicExport", "Return", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxSelected.setText(QtGui.QApplication.translate("alembicExport", "SELECTED", None, QtGui.QApplication.UnicodeUTF8))
        self.edtFrameEnd.setText(QtGui.QApplication.translate("alembicExport", "1210", None, QtGui.QApplication.UnicodeUTF8))
        self.edtFrameStart.setText(QtGui.QApplication.translate("alembicExport", "1001", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("alembicExport", "-", None, QtGui.QApplication.UnicodeUTF8))

import maya_rc
