# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../_sandbox/maya/scripts/ui/qt/bpSave.ui'
#
# Created: Mon Aug 03 18:09:13 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_bpSave(object):
    def setupUi(self, bpSave):
        bpSave.setObjectName("bpSave")
        bpSave.resize(613, 322)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        bpSave.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/img/icons/bpM.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        bpSave.setWindowIcon(icon)
        bpSave.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(31, 31, 31);")
        self.lblImage = QtGui.QLabel(bpSave)
        self.lblImage.setGeometry(QtCore.QRect(5, 5, 421, 171))
        self.lblImage.setText("")
        self.lblImage.setPixmap(QtGui.QPixmap(":/shot/img/shot/000.png"))
        self.lblImage.setScaledContents(True)
        self.lblImage.setObjectName("lblImage")
        self.cbxPublish = QtGui.QCheckBox(bpSave)
        self.cbxPublish.setGeometry(QtCore.QRect(520, 196, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.cbxPublish.setFont(font)
        self.cbxPublish.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.cbxPublish.setStyleSheet("")
        self.cbxPublish.setTristate(False)
        self.cbxPublish.setObjectName("cbxPublish")
        self.edtSavePath = QtGui.QLineEdit(bpSave)
        self.edtSavePath.setGeometry(QtCore.QRect(85, 194, 361, 26))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.edtSavePath.setFont(font)
        self.edtSavePath.setReadOnly(True)
        self.edtSavePath.setObjectName("edtSavePath")
        self.btnFolder = QtGui.QPushButton(bpSave)
        self.btnFolder.setGeometry(QtCore.QRect(485, 195, 24, 24))
        self.btnFolder.setStyleSheet("background-color: rgb(56, 56, 56);")
        self.btnFolder.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/btn/img/btn/folderBtn24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFolder.setIcon(icon1)
        self.btnFolder.setIconSize(QtCore.QSize(22, 22))
        self.btnFolder.setObjectName("btnFolder")
        self.btnSave = QtGui.QPushButton(bpSave)
        self.btnSave.setGeometry(QtCore.QRect(520, 230, 81, 31))
        self.btnSave.setStyleSheet("background-color: rgb(56, 56, 56);")
        self.btnSave.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/btn/img/btn/btnSave.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSave.setIcon(icon2)
        self.btnSave.setIconSize(QtCore.QSize(32, 32))
        self.btnSave.setObjectName("btnSave")
        self.btnCancel = QtGui.QPushButton(bpSave)
        self.btnCancel.setGeometry(QtCore.QRect(520, 270, 81, 23))
        self.btnCancel.setStyleSheet("background-color: rgb(56, 56, 56);")
        self.btnCancel.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/btn/img/btn/denialBtn24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCancel.setIcon(icon3)
        self.btnCancel.setIconSize(QtCore.QSize(23, 23))
        self.btnCancel.setObjectName("btnCancel")
        self.edtComment = QtGui.QPlainTextEdit(bpSave)
        self.edtComment.setGeometry(QtCore.QRect(10, 230, 501, 61))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.edtComment.setFont(font)
        self.edtComment.setFrameShape(QtGui.QFrame.Box)
        self.edtComment.setFrameShadow(QtGui.QFrame.Plain)
        self.edtComment.setLineWidth(1)
        self.edtComment.setMidLineWidth(0)
        self.edtComment.setPlainText("")
        self.edtComment.setBackgroundVisible(False)
        self.edtComment.setCenterOnScroll(False)
        self.edtComment.setObjectName("edtComment")
        self.edtMetaData = QtGui.QPlainTextEdit(bpSave)
        self.edtMetaData.setGeometry(QtCore.QRect(440, 40, 161, 131))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(9)
        font.setWeight(50)
        font.setBold(False)
        self.edtMetaData.setFont(font)
        self.edtMetaData.setFrameShape(QtGui.QFrame.Box)
        self.edtMetaData.setFrameShadow(QtGui.QFrame.Plain)
        self.edtMetaData.setLineWidth(1)
        self.edtMetaData.setReadOnly(True)
        self.edtMetaData.setObjectName("edtMetaData")
        self.btnHelp = QtGui.QPushButton(bpSave)
        self.btnHelp.setGeometry(QtCore.QRect(585, 300, 16, 16))
        self.btnHelp.setStyleSheet("background-color: rgb(56, 56, 56);")
        self.btnHelp.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/btn/img/btn/helpBtn24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnHelp.setIcon(icon4)
        self.btnHelp.setIconSize(QtCore.QSize(16, 16))
        self.btnHelp.setObjectName("btnHelp")
        self.btnEmail = QtGui.QPushButton(bpSave)
        self.btnEmail.setGeometry(QtCore.QRect(560, 300, 16, 16))
        self.btnEmail.setStyleSheet("background-color: rgb(56, 56, 56);")
        self.btnEmail.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/btn/img/btn/mailBtn24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEmail.setIcon(icon5)
        self.btnEmail.setIconSize(QtCore.QSize(16, 16))
        self.btnEmail.setObjectName("btnEmail")
        self.btnMessage = QtGui.QPushButton(bpSave)
        self.btnMessage.setGeometry(QtCore.QRect(520, 300, 16, 16))
        self.btnMessage.setStyleSheet("background-color: rgb(56, 56, 56);")
        self.btnMessage.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/btn/img/btn/inboxBtn24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMessage.setIcon(icon6)
        self.btnMessage.setIconSize(QtCore.QSize(16, 16))
        self.btnMessage.setObjectName("btnMessage")
        self.line = QtGui.QFrame(bpSave)
        self.line.setGeometry(QtCore.QRect(15, 175, 591, 20))
        self.line.setStyleSheet("")
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lblShotNr = QtGui.QLabel(bpSave)
        self.lblShotNr.setGeometry(QtCore.QRect(280, 150, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Nexa Bold")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.lblShotNr.setFont(font)
        self.lblShotNr.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblShotNr.setStyleSheet("background-color: \'transparent\';")
        self.lblShotNr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblShotNr.setObjectName("lblShotNr")
        self.lblBanner = QtGui.QLabel(bpSave)
        self.lblBanner.setGeometry(QtCore.QRect(400, 10, 24, 24))
        self.lblBanner.setStyleSheet("background-color: \'transparent\';")
        self.lblBanner.setText("")
        self.lblBanner.setPixmap(QtGui.QPixmap(":/banner/img/banner/LIGHT.png"))
        self.lblBanner.setScaledContents(True)
        self.lblBanner.setObjectName("lblBanner")
        self.lblVersion = QtGui.QLabel(bpSave)
        self.lblVersion.setGeometry(QtCore.QRect(15, 160, 46, 13))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setWeight(75)
        font.setBold(True)
        self.lblVersion.setFont(font)
        self.lblVersion.setStyleSheet("background-color: \'transparent\';")
        self.lblVersion.setObjectName("lblVersion")
        self.cbxUser = QtGui.QComboBox(bpSave)
        self.cbxUser.setGeometry(QtCore.QRect(470, 9, 131, 22))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.cbxUser.setFont(font)
        self.cbxUser.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cbxUser.setStyleSheet("background-color: rgb(56, 56, 56);")
        self.cbxUser.setEditable(False)
        self.cbxUser.setInsertPolicy(QtGui.QComboBox.InsertAtBottom)
        self.cbxUser.setFrame(False)
        self.cbxUser.setObjectName("cbxUser")
        self.lblUser = QtGui.QLabel(bpSave)
        self.lblUser.setGeometry(QtCore.QRect(440, 5, 30, 30))
        self.lblUser.setStyleSheet("background-color: \'transparent\';")
        self.lblUser.setText("")
        self.lblUser.setPixmap(QtGui.QPixmap(":/user/img/user/_default.png"))
        self.lblUser.setScaledContents(True)
        self.lblUser.setObjectName("lblUser")
        self.lblStatus = QtGui.QLabel(bpSave)
        self.lblStatus.setGeometry(QtCore.QRect(13, 192, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.lblStatus.setFont(font)
        self.lblStatus.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblStatus.setObjectName("lblStatus")
        self.lblSlash = QtGui.QLabel(bpSave)
        self.lblSlash.setGeometry(QtCore.QRect(72, 192, 10, 31))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.lblSlash.setFont(font)
        self.lblSlash.setTextFormat(QtCore.Qt.AutoText)
        self.lblSlash.setObjectName("lblSlash")
        self.btnVersionUp = QtGui.QPushButton(bpSave)
        self.btnVersionUp.setGeometry(QtCore.QRect(455, 195, 21, 12))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setWeight(75)
        font.setBold(True)
        self.btnVersionUp.setFont(font)
        self.btnVersionUp.setStyleSheet("background-color: rgb(56, 56, 56);")
        self.btnVersionUp.setObjectName("btnVersionUp")
        self.btnVersionDown = QtGui.QPushButton(bpSave)
        self.btnVersionDown.setGeometry(QtCore.QRect(455, 207, 21, 12))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setWeight(75)
        font.setBold(True)
        self.btnVersionDown.setFont(font)
        self.btnVersionDown.setStyleSheet("background-color: rgb(56, 56, 56);")
        self.btnVersionDown.setObjectName("btnVersionDown")
        self.edtPath = QtGui.QLineEdit(bpSave)
        self.edtPath.setEnabled(True)
        self.edtPath.setGeometry(QtCore.QRect(10, 299, 501, 18))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.edtPath.setFont(font)
        self.edtPath.setFrame(False)
        self.edtPath.setReadOnly(True)
        self.edtPath.setObjectName("edtPath")

        self.retranslateUi(bpSave)
        QtCore.QMetaObject.connectSlotsByName(bpSave)

    def retranslateUi(self, bpSave):
        bpSave.setWindowTitle(QtGui.QApplication.translate("bpSave", "bpSave", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxPublish.setText(QtGui.QApplication.translate("bpSave", "PUBLISH", None, QtGui.QApplication.UnicodeUTF8))
        self.edtSavePath.setText(QtGui.QApplication.translate("bpSave", "140_LIGHT_v003_ar.ma", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSave.setShortcut(QtGui.QApplication.translate("bpSave", "Return", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCancel.setShortcut(QtGui.QApplication.translate("bpSave", "Esc", None, QtGui.QApplication.UnicodeUTF8))
        self.edtMetaData.setPlainText(QtGui.QApplication.translate("bpSave", "Resolution:    2048 x 858\n"
"\n"
"FPS:    25 FPS\n"
"\n"
"Frames:    1001 - 1245", None, QtGui.QApplication.UnicodeUTF8))
        self.lblShotNr.setText(QtGui.QApplication.translate("bpSave", "140", None, QtGui.QApplication.UnicodeUTF8))
        self.lblVersion.setText(QtGui.QApplication.translate("bpSave", "v.0.01", None, QtGui.QApplication.UnicodeUTF8))
        self.lblStatus.setText(QtGui.QApplication.translate("bpSave", "WORK", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSlash.setText(QtGui.QApplication.translate("bpSave", "|", None, QtGui.QApplication.UnicodeUTF8))
        self.btnVersionUp.setText(QtGui.QApplication.translate("bpSave", "↑", None, QtGui.QApplication.UnicodeUTF8))
        self.btnVersionDown.setText(QtGui.QApplication.translate("bpSave", "↓", None, QtGui.QApplication.UnicodeUTF8))
        self.edtPath.setText(QtGui.QApplication.translate("bpSave", "140_LIGHT_v003_ar.ma", None, QtGui.QApplication.UnicodeUTF8))

import bpMaya_rc
