# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../_sandbox/maya/scripts/ui/qt/bpSave.ui'
#
# Created: Thu Jul 23 16:49:13 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_bpSave(object):
    def setupUi(self, bpSave):
        bpSave.setObjectName("bpSave")
        bpSave.resize(629, 318)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        bpSave.setFont(font)
        bpSave.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(31, 31, 31);")
        self.lblImage = QtGui.QLabel(bpSave)
        self.lblImage.setGeometry(QtCore.QRect(5, 5, 426, 183))
        self.lblImage.setText("")
        self.lblImage.setPixmap(QtGui.QPixmap(":/shot/img/shot/000.png"))
        self.lblImage.setScaledContents(True)
        self.lblImage.setObjectName("lblImage")
        self.cbxPublish = QtGui.QCheckBox(bpSave)
        self.cbxPublish.setGeometry(QtCore.QRect(540, 206, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.cbxPublish.setFont(font)
        self.cbxPublish.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.cbxPublish.setTristate(False)
        self.cbxPublish.setObjectName("cbxPublish")
        self.edtSavePath = QtGui.QLineEdit(bpSave)
        self.edtSavePath.setGeometry(QtCore.QRect(10, 204, 481, 26))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.edtSavePath.setFont(font)
        self.edtSavePath.setObjectName("edtSavePath")
        self.btnFolder = QtGui.QPushButton(bpSave)
        self.btnFolder.setGeometry(QtCore.QRect(500, 205, 24, 24))
        self.btnFolder.setStyleSheet("background-color: rgb(56, 56, 56);")
        self.btnFolder.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/btn/img/btn/folderBtn24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFolder.setIcon(icon)
        self.btnFolder.setIconSize(QtCore.QSize(22, 22))
        self.btnFolder.setObjectName("btnFolder")
        self.btnSave = QtGui.QPushButton(bpSave)
        self.btnSave.setGeometry(QtCore.QRect(540, 240, 81, 41))
        self.btnSave.setStyleSheet("background-color: rgb(56, 56, 56);")
        self.btnSave.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/btn/img/btn/btnSave.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSave.setIcon(icon1)
        self.btnSave.setIconSize(QtCore.QSize(32, 32))
        self.btnSave.setObjectName("btnSave")
        self.btnCancel = QtGui.QPushButton(bpSave)
        self.btnCancel.setGeometry(QtCore.QRect(540, 290, 81, 23))
        self.btnCancel.setStyleSheet("background-color: rgb(56, 56, 56);")
        self.btnCancel.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/btn/img/btn/denialBtn24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCancel.setIcon(icon2)
        self.btnCancel.setIconSize(QtCore.QSize(23, 23))
        self.btnCancel.setObjectName("btnCancel")
        self.edtComment = QtGui.QPlainTextEdit(bpSave)
        self.edtComment.setGeometry(QtCore.QRect(10, 240, 513, 71))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.edtComment.setFont(font)
        self.edtComment.setFrameShape(QtGui.QFrame.Box)
        self.edtComment.setFrameShadow(QtGui.QFrame.Plain)
        self.edtComment.setLineWidth(1)
        self.edtComment.setMidLineWidth(0)
        self.edtComment.setBackgroundVisible(False)
        self.edtComment.setCenterOnScroll(False)
        self.edtComment.setObjectName("edtComment")
        self.edtMetaData = QtGui.QPlainTextEdit(bpSave)
        self.edtMetaData.setGeometry(QtCore.QRect(440, 40, 181, 116))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(9)
        font.setWeight(50)
        font.setBold(False)
        self.edtMetaData.setFont(font)
        self.edtMetaData.setFrameShape(QtGui.QFrame.Box)
        self.edtMetaData.setFrameShadow(QtGui.QFrame.Plain)
        self.edtMetaData.setLineWidth(1)
        self.edtMetaData.setReadOnly(True)
        self.edtMetaData.setObjectName("edtMetaData")
        self.btnHelp = QtGui.QPushButton(bpSave)
        self.btnHelp.setGeometry(QtCore.QRect(595, 165, 24, 24))
        self.btnHelp.setStyleSheet("background-color: rgb(56, 56, 56);")
        self.btnHelp.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/btn/img/btn/helpBtn24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnHelp.setIcon(icon3)
        self.btnHelp.setIconSize(QtCore.QSize(22, 22))
        self.btnHelp.setObjectName("btnHelp")
        self.btnEmail = QtGui.QPushButton(bpSave)
        self.btnEmail.setGeometry(QtCore.QRect(560, 165, 24, 24))
        self.btnEmail.setStyleSheet("background-color: rgb(56, 56, 56);")
        self.btnEmail.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/btn/img/btn/mailBtn24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEmail.setIcon(icon4)
        self.btnEmail.setIconSize(QtCore.QSize(22, 22))
        self.btnEmail.setObjectName("btnEmail")
        self.btnMessage = QtGui.QPushButton(bpSave)
        self.btnMessage.setGeometry(QtCore.QRect(440, 165, 24, 24))
        self.btnMessage.setStyleSheet("background-color: rgb(56, 56, 56);")
        self.btnMessage.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/btn/img/btn/inboxBtn24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMessage.setIcon(icon5)
        self.btnMessage.setIconSize(QtCore.QSize(22, 22))
        self.btnMessage.setObjectName("btnMessage")
        self.line = QtGui.QFrame(bpSave)
        self.line.setGeometry(QtCore.QRect(5, 195, 616, 5))
        self.line.setStyleSheet("")
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lblShotNr = QtGui.QLabel(bpSave)
        self.lblShotNr.setGeometry(QtCore.QRect(285, 165, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Bebas Neue Bold")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.lblShotNr.setFont(font)
        self.lblShotNr.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblShotNr.setStyleSheet("background-color: \'transparent\';")
        self.lblShotNr.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblShotNr.setObjectName("lblShotNr")
        self.lblBanner = QtGui.QLabel(bpSave)
        self.lblBanner.setGeometry(QtCore.QRect(405, 10, 24, 24))
        self.lblBanner.setStyleSheet("background-color: \'transparent\';")
        self.lblBanner.setText("")
        self.lblBanner.setPixmap(QtGui.QPixmap(":/banner/img/banner/LIGHT.png"))
        self.lblBanner.setScaledContents(True)
        self.lblBanner.setObjectName("lblBanner")
        self.lblVersion = QtGui.QLabel(bpSave)
        self.lblVersion.setGeometry(QtCore.QRect(15, 170, 46, 13))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setWeight(75)
        font.setBold(True)
        self.lblVersion.setFont(font)
        self.lblVersion.setStyleSheet("background-color: \'transparent\';")
        self.lblVersion.setObjectName("lblVersion")
        self.cbxUser = QtGui.QComboBox(bpSave)
        self.cbxUser.setGeometry(QtCore.QRect(470, 9, 151, 22))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.cbxUser.setFont(font)
        self.cbxUser.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cbxUser.setStyleSheet("background-color: rgb(56, 56, 56);")
        self.cbxUser.setEditable(False)
        self.cbxUser.setInsertPolicy(QtGui.QComboBox.InsertAtBottom)
        self.cbxUser.setFrame(False)
        self.cbxUser.setObjectName("cbxUser")
        self.lblUser = QtGui.QLabel(bpSave)
        self.lblUser.setGeometry(QtCore.QRect(440, 5, 30, 30))
        self.lblUser.setStyleSheet("background-color: \'transparent\';")
        self.lblUser.setText("")
        self.lblUser.setPixmap(QtGui.QPixmap(":/user/img/user/_default.png"))
        self.lblUser.setScaledContents(True)
        self.lblUser.setObjectName("lblUser")

        self.retranslateUi(bpSave)
        QtCore.QMetaObject.connectSlotsByName(bpSave)

    def retranslateUi(self, bpSave):
        bpSave.setWindowTitle(QtGui.QApplication.translate("bpSave", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxPublish.setText(QtGui.QApplication.translate("bpSave", "PUBLISH", None, QtGui.QApplication.UnicodeUTF8))
        self.edtSavePath.setText(QtGui.QApplication.translate("bpSave", "[140]/WORK/140_LIGHT_v003_ar.ma", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSave.setShortcut(QtGui.QApplication.translate("bpSave", "Return", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCancel.setShortcut(QtGui.QApplication.translate("bpSave", "Esc", None, QtGui.QApplication.UnicodeUTF8))
        self.edtComment.setPlainText(QtGui.QApplication.translate("bpSave", "comment", None, QtGui.QApplication.UnicodeUTF8))
        self.edtMetaData.setPlainText(QtGui.QApplication.translate("bpSave", "Resolution:    2048 x 858\n"
"\n"
"FPS:    25 FPS\n"
"\n"
"Frames:    1001 - 1245", None, QtGui.QApplication.UnicodeUTF8))
        self.lblShotNr.setText(QtGui.QApplication.translate("bpSave", "140", None, QtGui.QApplication.UnicodeUTF8))
        self.lblVersion.setText(QtGui.QApplication.translate("bpSave", "v.0.01", None, QtGui.QApplication.UnicodeUTF8))

import bpMaya_rc
